{
  imports = [
    ./airline.nix
    ./barbar.nix
    ./bufferline.nix
    ./comment-nvim.nix
    ./cursorline.nix
    ./dap.nix
    ./gitsigns.nix
    ./indent-blankline.nix
    ./lsp-format.nix
    ./luasnip.nix
    ./nvim-autopairs.nix
    ./nvim-cmp.nix
    ./nvim-colorizer.nix
    ./nvim-tree.nix
    ./telescope.nix
    ./treesitter.nix
    ./which-key.nix
  ];
}
