{
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./cmp-buffer.nix
    ./cmp-nvim-lsp.nix
    ./cmp-path.nix
    ./cmp.nix
    ./cmp_luasnip.nix
    ./comment.nix
    ./comment.nix
    ./friendly-snippets.nix
    ./gitsigns.nix
    ./indent-blankline.nix
    ./lazygit.nix
    ./ledger.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./neorg.nix
    ./nvim-autopairs.nix
    ./nvim-colorizer.nix
    ./nvim-tree.nix
    ./project-nvim.nix
    ./surround.nix
    ./telescope.nix
    ./treesitter.nix
    ./which-key.nix
  ];
}
