{ pkgs, ... }:

{
    environment.systemPackages = with pkgs; [
     # transmission
     # transmission-gtk
     ark
     atool
     baobab
     bat
     binutils
     blanket
     bluez
     bottles
     bottom
     btop
     calcurse
     catppuccin-gtk
     chafa
     clang
     clipman
     cmake
     colordiff
     ctpv
     du-dust
     duf
     dunst
     elinks
     eva
     exa
     exiftool
     fd
     ffmpeg
     ffmpegthumbnailer
     file
     firefox
     fontconfig
     fontforge
     foot
     fzf
     gamescope
     gimp
     git
     glow
     gnome-epub-thumbnailer
     gnome.gnome-boxes
     gnome.gnome-calculator
     gnome.gnome-disk-utility
     gnome.gnome-themes-extra
     gnome.gnome-weather
     gnome.nautilus
     gnumake
     grim
     gtk-engine-murrine
     gtk3
     gtk4
     hexyl
     home-manager
     hyprpicker
     imagemagick
     imv
     isync
     jq 
     killall
     lazygit
     ledger
     lf
     libnotify
     libreoffice
     libsixel
     lxappearance-gtk2
     mcrcon
     mediainfo
     mlocate
     mpc-cli
     mpd
     mpv
     mpvScripts.sponsorblock
     mullvad
     mullvad-vpn
     musl
     ncdu
     ncmpcpp
     neofetch
     neovide
     neovim
     networkmanager_dmenu
     newsboat
     nmap
     nodePackages_latest.peerflix
     nodejs
     obs-studio
     odt2txt
     p7zip
     pamixer
     pandoc
     pass-wayland
     pciutils
     pinentry
     piper
     poetry
     polkit_gnome
     poppler_utils
     prismlauncher
     procs
     pulsemixer
     python3
     qemu
     ripdrag
     ripgrep
     ripgrep-all
     rofi-wayland
     rpcs3
     rustup
     sc-im
     scanmem
     scc
     sd
     skim
     slurp
     spotify
     sqlite
     steam
     swayidle
     swaylock
     swww
     telegram-desktop
     texlive.combined.scheme-full
     thunderbird
     tldr
     tree-sitter
     unrar
     unzip
     ventoy-full
     vimv-rs
     warp
     wev
     wget
     wl-clipboard
     xcodebuild
     xdg-desktop-portal
     xdg-desktop-portal-hyprland
     xdg-user-dirs
     xmlstarlet
     ydotool
     yt-dlp
     zafiro-icons
     zathura
     zoxide
     ];
}
