#!/usr/bin/env bash

selected="$(ps -a -u $USER | \
            fuzzel -d -w 100 -p "Rechercher le processus à terminer : " \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Oui\nNon" | \
            fuzzel -d -w 100 -p "$selected va être terminé, êtes-vous sûr ? ")"

    if [[ $answer == "Oui" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
