{ config, pkgs, ... }:
{
    environment.systemPackages = with pkgs; [
     ark
     atool
     bat
     binutils
     bluez
     bottles
     bottom
     btop
     calcurse
     chafa
     cinnamon.warpinator
     foot
     clang
     clipman
     mpvScripts.sponsorblock
     colordiff
     ctpv
     du-dust
     duf
     pciutils
     dunst
     elinks
     eva
     exa
     exiftool
     fd
     ffmpeg
     ffmpegthumbnailer
     file
     firefox
     fontconfig
     fontforge
     fzf
     gcc
     git
     glibc
     glow
     gnome-epub-thumbnailer
     home-manager
     xdg-user-dirs
     gnome.gnome-boxes
     gnome.gnome-disk-utility
     gnumake
     libnotify
     grim
     hexyl
     hyprpicker
     imagemagick
     imv
     jq 
     killall
     lazygit
     ledger
     lf
     libreoffice
     libsixel
     lxappearance-gtk2
     mcrcon
     mediainfo
     mlocate
     mpc-cli
     mpd
     mpv
     mullvad
     mullvad-vpn
     musl
     mutt-wizard
     ncmpcpp
     neofetch
     neomutt
     neovim
     networkmanager_dmenu
     newsboat
     newsboat
     nmap
     nodePackages_latest.peerflix
     nodejs
     obs-studio
     odt2txt
     p7zip
     pamixer
     pandoc
     pass-wayland
     pcmanfm
     pinentry
     piper
     polkit_gnome
     poppler_utils
     prismlauncher
     procs
     pulsemixer
     python3
     qemu
     steam
     ripdrag
     ripgrep
     ripgrep-all
     rofi-wayland
     rpcs3
     rustup
     sc-im
     scanmem
     silver-searcher
     slurp
     spotify
     sqlite
     swayidle
     swaylock
     swww
     telegram-desktop
     texlive.combined.scheme-full
     tldr
     transmission
     transmission-gtk
     tree-sitter
     unrar
     unzip
     ventoy-full
     vimv-rs
     wev
     wget
     whitesur-gtk-theme
     wl-clipboard
     xcodebuild
     xdg-desktop-portal
     xdg-desktop-portal-hyprland
     xmlstarlet
     ydotool
     yt-dlp
     zafiro-icons
     zathura
     zoxide
     ];
}
